version: 2
jobs:

  build-node7:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm run coverage
      - run: npm run codecov

  build-node6:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: npm install
      - run: npm run coverage
      - run: npm run codecov

workflows:
  version: 2
  build:
    jobs:
      - build-node7
      - build-node6